### ISSUE TITLE
[BUG] in clvm article

### ISSUE THREAD

**Issue by asterkin** [BstLabs/medium-articles#4]
1. "cloud instances over an ssh connection" - mistake, should be "over ssm connection". We run ssh and http over ssm.
2. "struggle of using the web interface to create, access, and configure several services to handle cloud instances" - not exactly. Web interfaces and/command lines to start/stop and configure VM instances. We do not create cloud resources via clvm.
3. VSCODE Remote
4. ssm                 Session manager utilities
   vscode              Microsoft vscode utilities - need to be consistent with all other command helps which all are low case; it's an issue for clvm itself btw
5. "Next, we connect to our running instance via clvm connect <instance_name> and et voilà! We can operate within our instance from the local terminal." clvm connect should start the instance automatically and be robust with regard to this. I prefer to postpone the publication but to do it right.
6. You need to mention that it uses default profile and to explain how to use a non-default one mentioning that supporting multiple clouds will follow
7. "Using local VSCode with cloud instances" - better "Working with VSCode remote over SSH" and to make it the main topic of the article, even mb bypassing the port redirection.
8.

**Comment by ShahriyarR** [comment]
@asterkin I am interested in 8th one :D
